using System.Text.Json;
using System.Text.RegularExpressions;
using ChessEngine.Engine;

namespace ChessBin.Web.Tests;

/// <summary>
/// Guards the pre-rendered opening pages and the line index they are built from, both
/// generated by <c>tools/OpeningPages</c> and committed rather than built.
/// <para>
/// These pages exist because a crawler never runs the app, so they are the only thing it can
/// read — which means a fault in them is invisible to anyone testing the site in a browser.
/// A line that does not play, a slug that disagrees with the reader's, a link to a page that
/// was never generated, or a page missing from the sitemap would all ship silently.
/// </para>
/// </summary>
public sealed class OpeningPageTests
{
    private static string Wwwroot
    {
        get
        {
            var dir = new DirectoryInfo(TestContext.CurrentContext.TestDirectory);
            while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, "ChessBin.Web", "wwwroot")))
                dir = dir.Parent;
            return Path.Combine(dir!.FullName, "ChessBin.Web", "wwwroot");
        }
    }

    private static string OpeningsDir => Path.Combine(Wwwroot, "openings");
    private static string LinesDir => Path.Combine(OpeningsDir, "lines");

    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    private static OpeningLineManifest LineManifest() =>
        JsonSerializer.Deserialize<OpeningLineManifest>(
            File.ReadAllText(Path.Combine(LinesDir, "manifest.json")), Json)!;

    /// <summary>Every shipped line, paired with the shard number it was actually stored in.</summary>
    private static List<(int Shard, OpeningLine Line)> AllLines()
    {
        var all = new List<(int, OpeningLine)>();
        foreach (string file in Directory.EnumerateFiles(LinesDir, "shard-*.json").OrderBy(f => f, StringComparer.Ordinal))
        {
            int shard = int.Parse(Path.GetFileNameWithoutExtension(file)["shard-".Length..]);
            var lines = JsonSerializer.Deserialize<List<OpeningLine>>(File.ReadAllText(file), Json)!;
            foreach (OpeningLine line in lines) all.Add((shard, line));
        }
        return all;
    }

    /// <summary>The slug of every opening that actually has a page, from the directories on disk.</summary>
    private static HashSet<string> GeneratedSlugs() =>
        [.. Directory.EnumerateDirectories(OpeningsDir)
            .Select(Path.GetFileName)
            .Where(name => name != "lines" && File.Exists(Path.Combine(OpeningsDir, name!, "index.html")))
            .Select(name => name!)];

    private static string PageOf(string slug) =>
        File.ReadAllText(Path.Combine(OpeningsDir, slug, "index.html"));

    // ── The line index ──────────────────────────────────────────────────────────

    [Test]
    public void TheLineManifestDescribesTheShardsThatAreActuallyOnDisk()
    {
        OpeningLineManifest manifest = LineManifest();
        var all = AllLines();

        Assert.Multiple(() =>
        {
            Assert.That(manifest.Version, Is.EqualTo(1));
            Assert.That(Directory.EnumerateFiles(LinesDir, "shard-*.json").Count(),
                Is.EqualTo(manifest.Shards), "manifest shard count disagrees with the files");
            Assert.That(all, Has.Count.EqualTo(manifest.Lines), "manifest line count is wrong");
            Assert.That(manifest.Lines, Is.GreaterThan(3_000), "the ECO tables should contribute thousands of names");
        });
    }

    [Test]
    public void EveryLineSitsInTheShardTheReaderWillLookIn()
    {
        int shards = LineManifest().Shards;

        Assert.Multiple(() =>
        {
            foreach ((int shard, OpeningLine line) in AllLines())
            {
                Assert.That(OpeningExplorer.ShardOf(line.Slug, shards), Is.EqualTo(shard),
                    $"'{line.Slug}' shipped in shard {shard} but the reader looks in " +
                    $"{OpeningExplorer.ShardOf(line.Slug, shards)} — the generator's hash has drifted");
            }
        });
    }

    /// <summary>
    /// The slug rule lives twice — in <c>tools/OpeningPages</c> and in the reader — because a
    /// console tool cannot reference a Blazor WebAssembly project. This is the assertion that
    /// keeps the copies honest, the same guarantee the shard hash gets.
    /// </summary>
    [Test]
    public void EverySlugIsTheOneTheReaderWouldDeriveFromTheName()
    {
        Assert.Multiple(() =>
        {
            foreach ((_, OpeningLine line) in AllLines())
            {
                Assert.That(line.Slug, Is.EqualTo(OpeningExplorer.SlugOf(line.Name)),
                    $"'{line.Name}' shipped as '{line.Slug}' but the reader derives " +
                    $"'{OpeningExplorer.SlugOf(line.Name)}'");
            }
        });
    }

    [Test]
    public void EverySlugIsUniqueAndSafeInAUrl()
    {
        var all = AllLines().Select(l => l.Line).ToList();
        var duplicates = all.GroupBy(l => l.Slug, StringComparer.Ordinal)
            .Where(g => g.Count() > 1)
            .Select(g => $"'{g.Key}' from {string.Join(" / ", g.Select(l => l.Name))}")
            .ToArray();

        Assert.Multiple(() =>
        {
            Assert.That(duplicates, Is.Empty, "two openings would share a page: " + string.Join("; ", duplicates));

            foreach (OpeningLine line in all)
            {
                Assert.That(line.Slug, Does.Match("^[a-z0-9]+(-[a-z0-9]+)*$"),
                    $"'{line.Name}' produced a slug that needs escaping in a URL: '{line.Slug}'");
                Assert.That(line.Eco, Is.Not.Empty, $"'{line.Name}' shipped without an ECO code");
            }
        });
    }

    /// <summary>
    /// The whole point of the line index: a page claims an opening is reached by a particular
    /// move order, so that move order had better play and had better land where it says.
    /// </summary>
    [Test]
    public void EveryLinePlaysAndEndsOnThePositionItNames()
    {
        var engine = new Engine();
        int problems = 0;

        Assert.Multiple(() =>
        {
            foreach ((_, OpeningLine line) in AllLines())
            {
                if (problems >= 5) break;

                Assert.That(line.Sans, Has.Count.EqualTo(line.Ucis.Count),
                    $"'{line.Name}' has {line.Sans.Count} moves in notation and {line.Ucis.Count} in coordinates");
                if (line.Sans.Count != line.Ucis.Count) { problems++; continue; }

                engine.SetPosition(ChessGameSession.StartingFen);
                engine.GenerateValidMoves();

                bool played = true;
                foreach (string uci in line.Ucis)
                {
                    if (PuzzleData.TryApplyUci(engine, uci)) continue;
                    Assert.Fail($"'{line.Name}' does not play: {uci} is illegal in {engine.FEN}");
                    played = false;
                    problems++;
                    break;
                }

                if (!played) continue;

                Assert.That(OpeningExplorer.KeyOf(engine.FEN), Is.EqualTo(line.Key),
                    $"'{line.Name}' ends on a different position than it claims");
                if (OpeningExplorer.KeyOf(engine.FEN) != line.Key) problems++;
            }
        });
    }

    // ── The generated pages ─────────────────────────────────────────────────────

    [Test]
    public void EveryGeneratedPageBelongsToALineThatShipped()
    {
        var slugs = AllLines().Select(l => l.Line.Slug).ToHashSet(StringComparer.Ordinal);

        Assert.Multiple(() =>
        {
            foreach (string generated in GeneratedSlugs())
            {
                Assert.That(slugs, Does.Contain(generated),
                    $"openings/{generated}/ has no entry in the line index — a stale page from an earlier run");
            }
        });
    }

    /// <summary>
    /// Nothing else would notice a page linking to a route that was never generated: it is a
    /// 404 for a reader and a dead end for a crawler, and the app's own router would answer it
    /// with the explorer at move one, so even clicking it looks almost right.
    /// </summary>
    [Test]
    public void NoGeneratedPageLinksToAPageThatDoesNotExist()
    {
        HashSet<string> generated = GeneratedSlugs();
        var broken = new List<string>();

        foreach (string slug in generated.Concat(["."]))
        {
            string file = slug == "." ? Path.Combine(OpeningsDir, "index.html") : Path.Combine(OpeningsDir, slug, "index.html");
            foreach (Match link in Regex.Matches(File.ReadAllText(file), @"href=""/openings/(?<slug>[^""/]+)/"""))
            {
                string target = link.Groups["slug"].Value;
                if (!generated.Contains(target)) broken.Add($"{slug} → {target}");
            }
        }

        Assert.That(broken, Is.Empty, "generated pages link to routes that were never written: " + string.Join("; ", broken.Take(10)));
    }

    [Test]
    public void NoGeneratedPageIsOrphaned()
    {
        HashSet<string> generated = GeneratedSlugs();
        var linked = new HashSet<string>(StringComparer.Ordinal);

        foreach (string file in generated.Select(s => Path.Combine(OpeningsDir, s, "index.html"))
                                         .Append(Path.Combine(OpeningsDir, "index.html")))
        {
            string self = Path.GetFileName(Path.GetDirectoryName(file))!;
            foreach (Match link in Regex.Matches(File.ReadAllText(file), @"href=""/openings/(?<slug>[^""/]+)/"""))
            {
                if (link.Groups["slug"].Value != self) linked.Add(link.Groups["slug"].Value);
            }
        }

        string[] orphans = [.. generated.Except(linked).Order(StringComparer.Ordinal)];
        Assert.That(orphans, Is.Empty,
            "nothing links to these pages, so a crawler can only find them through the sitemap: " +
            string.Join(", ", orphans.Take(10)));
    }

    [Test]
    public void TheSitemapAndTheGeneratedPagesAgree()
    {
        string sitemap = File.ReadAllText(Path.Combine(Wwwroot, "sitemap.xml"));
        var listed = Regex.Matches(sitemap, @"<loc>https://chessbin\.com/openings/(?<slug>[^</]+)/</loc>")
            .Select(m => m.Groups["slug"].Value)
            .ToHashSet(StringComparer.Ordinal);

        HashSet<string> generated = GeneratedSlugs();

        Assert.Multiple(() =>
        {
            Assert.That(listed.Except(generated), Is.Empty, "the sitemap lists opening pages that do not exist");
            Assert.That(generated.Except(listed), Is.Empty, "opening pages exist that the sitemap does not list");
        });
    }

    [Test]
    public void EveryGeneratedPageDeclaresItsOwnCanonicalAndAUniqueTitle()
    {
        var titles = new Dictionary<string, string>(StringComparer.Ordinal);

        Assert.Multiple(() =>
        {
            foreach (string slug in GeneratedSlugs().Order(StringComparer.Ordinal))
            {
                string html = PageOf(slug);

                Match canonical = Regex.Match(html, @"<link rel=""canonical"" href=""(?<url>[^""]+)""");
                Assert.That(canonical.Success, Is.True, $"openings/{slug}/ has no canonical link");
                Assert.That(canonical.Groups["url"].Value, Is.EqualTo($"https://chessbin.com/openings/{slug}/"),
                    $"openings/{slug}/ points its canonical at another page, which de-indexes it");

                Match title = Regex.Match(html, @"<title>(?<t>[^<]+)</title>");
                Assert.That(title.Success, Is.True, $"openings/{slug}/ has no title");
                Assert.That(titles.TryAdd(title.Groups["t"].Value, slug), Is.True,
                    $"openings/{slug}/ shares a title with openings/{titles.GetValueOrDefault(title.Groups["t"].Value)}/");
            }
        });
    }

    /// <summary>
    /// The generated pages carry the same hand-written chrome as the boot pages, so they are
    /// subject to the same rules: the nav has to match the app's, and the copy is for chess
    /// players. <c>BootPageTests</c> checks the seven route pages; this checks the hundreds.
    /// </summary>
    [Test]
    public void EveryGeneratedPageCarriesTheSameNavigationAsTheApp()
    {
        string navRazor = File.ReadAllText(Path.Combine(
            Directory.GetParent(Wwwroot)!.FullName, "Layout", "SiteNav.razor"));
        string[] labels = [.. Regex.Matches(navRazor, @"<span>([^<]+)</span>").Select(m => m.Groups[1].Value)];
        Assert.That(labels, Is.Not.Empty, "could not read the nav out of SiteNav.razor");

        Assert.Multiple(() =>
        {
            foreach (string slug in GeneratedSlugs().Order(StringComparer.Ordinal))
            {
                string html = PageOf(slug);

                string[] found = [.. Regex.Matches(html, @"<li><a href=""[^""]*""[^>]*>.*?<span>([^<]+)</span></a></li>")
                    .Select(m => m.Groups[1].Value)];
                Assert.That(found, Is.EqualTo(labels), $"openings/{slug}/ nav is out of step with SiteNav.razor");

                string[] active = [.. Regex.Matches(html, @"<li><a href=""(?<href>[^""]*)"" class=""active""")
                    .Select(m => m.Groups["href"].Value)];
                Assert.That(active, Has.Length.EqualTo(1), $"openings/{slug}/ must mark exactly one nav item active");
                Assert.That(active[0], Is.EqualTo("/openings/"), $"openings/{slug}/ marks {active[0]} active");
            }
        });
    }

    [Test]
    public void NoGeneratedPageExplainsTheImplementationToThePlayer()
    {
        string[] banned = ["WebAssembly", "neural network", "the repository", "open source"];

        Assert.Multiple(() =>
        {
            foreach (string slug in GeneratedSlugs().Order(StringComparer.Ordinal))
            {
                Match body = Regex.Match(PageOf(slug), @"<main class=""page"">(?<copy>.*?)</main>", RegexOptions.Singleline);
                Assert.That(body.Success, Is.True, $"openings/{slug}/ has no page content");

                foreach (string phrase in banned)
                {
                    Assert.That(body.Groups["copy"].Value, Does.Not.Contain(phrase).IgnoreCase,
                        $"openings/{slug}/ explains \"{phrase}\" to an audience that came to play chess");
                }
            }
        });
    }

    /// <summary>
    /// The board on a page is drawn from the position key by the generator, which keeps its own
    /// copy of the piece glyphs — <c>ChessBin.Web/Pieces.cs</c> is keyed by the engine's enums
    /// and a console tool cannot reference it. A drifted glyph would render a board that is
    /// subtly the wrong pieces, which nothing else would catch.
    /// </summary>
    [Test]
    public void EveryBoardShowsThePositionItsLineEndsOn()
    {
        var byName = AllLines().ToDictionary(l => l.Line.Slug, l => l.Line, StringComparer.Ordinal);

        Assert.Multiple(() =>
        {
            foreach (string slug in GeneratedSlugs().Order(StringComparer.Ordinal))
            {
                OpeningLine line = byName[slug];
                string[] drawn = [.. Regex.Matches(PageOf(slug), @"<span class=""piece [a-z-]+"">(?<glyph>[^<]+)</span>")
                    .Select(m => m.Groups["glyph"].Value)];

                string[] expected = [.. Expected(line.Key)];
                Assert.That(drawn, Is.EqualTo(expected),
                    $"openings/{slug}/ draws a board that is not the position {line.Name} ends on");
            }
        });

        // The placement field, read the way the generator reads it, but resolved through the
        // app's own glyph table rather than the generator's copy.
        static IEnumerable<string> Expected(string key)
        {
            foreach (char c in key.Split(' ')[0])
            {
                if (c is '/' or >= '1' and <= '8') continue;
                ChessPieceColor color = char.IsUpper(c) ? ChessPieceColor.White : ChessPieceColor.Black;
                ChessPieceType type = char.ToLowerInvariant(c) switch
                {
                    'k' => ChessPieceType.King,
                    'q' => ChessPieceType.Queen,
                    'r' => ChessPieceType.Rook,
                    'b' => ChessPieceType.Bishop,
                    'n' => ChessPieceType.Knight,
                    _ => ChessPieceType.Pawn,
                };
                yield return Pieces.Glyph(type, color);
            }
        }
    }
}
