using System.Text.Json;
using ChessEngine.Engine;

namespace ChessBin.Web.Tests;

/// <summary>
/// Guards the committed opening data, which is generated by <c>tools/OpeningImport</c> and
/// never regenerated at build time. Two things could break it silently: a bad import, and the
/// importer's shard hash drifting away from the reader's copy of it. Both would show up in
/// production as an explorer that says "not in the book" for positions that are in the book.
/// </summary>
public sealed class OpeningDataTests
{
    private static string Wwwroot
    {
        get
        {
            var dir = new DirectoryInfo(TestContext.CurrentContext.TestDirectory);
            while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, "ChessBin.Web", "wwwroot")))
                dir = dir.Parent;
            return Path.Combine(dir!.FullName, "ChessBin.Web", "wwwroot");
        }
    }

    private static string OpeningsDir => Path.Combine(Wwwroot, "openings");

    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    private static OpeningManifest Manifest() =>
        JsonSerializer.Deserialize<OpeningManifest>(
            File.ReadAllText(Path.Combine(OpeningsDir, "manifest.json")), Json)!;

    /// <summary>Every shipped position, paired with the shard number it was actually stored in.</summary>
    private static List<(int Shard, OpeningPosition Position)> AllPositions()
    {
        var all = new List<(int, OpeningPosition)>();
        foreach (string file in Directory.EnumerateFiles(OpeningsDir, "shard-*.json").OrderBy(f => f))
        {
            int shard = int.Parse(Path.GetFileNameWithoutExtension(file)["shard-".Length..]);
            var positions = JsonSerializer.Deserialize<List<OpeningPosition>>(File.ReadAllText(file), Json)!;
            foreach (OpeningPosition position in positions) all.Add((shard, position));
        }
        return all;
    }

    [Test]
    public void TheManifestDescribesTheShardsThatAreActuallyOnDisk()
    {
        OpeningManifest manifest = Manifest();
        var all = AllPositions();

        Assert.Multiple(() =>
        {
            Assert.That(manifest.Version, Is.EqualTo(1));
            Assert.That(Directory.EnumerateFiles(OpeningsDir, "shard-*.json").Count(),
                Is.EqualTo(manifest.Shards), "manifest shard count disagrees with the files");
            Assert.That(all, Has.Count.EqualTo(manifest.Positions), "manifest position count is wrong");
            Assert.That(all.Count(p => p.Position.Name is not null), Is.EqualTo(manifest.Named));
            Assert.That(manifest.Lines, Is.GreaterThan(3_000), "the ECO tables should contribute thousands of lines");
        });
    }

    /// <summary>
    /// The one that matters most. <c>OpeningExplorer.ShardOf</c> is a deliberate copy of the
    /// importer's hash — a console tool cannot reference a Blazor project — so this asserts
    /// the copy still agrees with where the importer actually put every key. If it ever
    /// disagrees the explorer fetches the wrong file and finds nothing, with no error.
    /// </summary>
    [Test]
    public void EveryPositionSitsInTheShardTheReaderWillLookIn()
    {
        int shards = Manifest().Shards;

        var misfiled = AllPositions()
            .Where(p => OpeningExplorer.ShardOf(p.Position.Key, shards) != p.Shard)
            .Select(p => $"{p.Position.Key} is in shard {p.Shard}, reader looks in {OpeningExplorer.ShardOf(p.Position.Key, shards)}")
            .Take(5)
            .ToArray();

        Assert.That(misfiled, Is.Empty, "importer and reader disagree on sharding: " + string.Join("; ", misfiled));
    }

    [Test]
    public void NoPositionIsShippedTwice()
    {
        var duplicates = AllPositions()
            .GroupBy(p => p.Position.Key, StringComparer.Ordinal)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .Take(5)
            .ToArray();

        Assert.That(duplicates, Is.Empty, "duplicate keys: " + string.Join("; ", duplicates));
    }

    [Test]
    public void EveryKeyIsTheFirstFourFieldsOfAFen()
    {
        var malformed = AllPositions()
            .Select(p => p.Position.Key)
            .Where(k => k.Split(' ').Length != 4)
            .Take(5)
            .ToArray();

        Assert.That(malformed, Is.Empty, "keys must be placement/side/castling/ep: " + string.Join("; ", malformed));
    }

    [Test]
    public void AnythingWithANameAlsoCarriesItsEcoCode()
    {
        var unclassified = AllPositions()
            .Select(p => p.Position)
            .Where(p => p.Name is not null && string.IsNullOrWhiteSpace(p.Eco))
            .Select(p => p.Name!)
            .Take(5)
            .ToArray();

        Assert.That(unclassified, Is.Empty, "named but no ECO: " + string.Join("; ", unclassified));
    }

    /// <summary>
    /// Replays the whole set through the engine. This is the equivalent of PuzzleDataTests:
    /// a move that ships is a move that provably plays, and the SAN shown beside it is the
    /// SAN the engine agrees with.
    /// </summary>
    [Test]
    public void EveryMoveIsLegalInThePositionItIsListedUnder()
    {
        // One Engine for the whole run — its constructor loads the opening book, and paying
        // that 8,000 times would dominate the test.
        var engine = new Engine();
        var problems = new List<string>();

        foreach ((_, OpeningPosition position) in AllPositions())
        {
            foreach (OpeningMove move in position.Moves)
            {
                engine.SetPosition(position.Key + " 0 1");
                engine.GenerateValidMoves();

                if (!PuzzleData.TryApplyUci(engine, move.Uci))
                {
                    problems.Add($"{move.San} ({move.Uci}) is not legal in {position.Key}");
                    if (problems.Count >= 5) break;
                }
            }
            if (problems.Count >= 5) break;
        }

        Assert.That(problems, Is.Empty, string.Join("; ", problems));
    }

    /// <summary>
    /// Each move carries the name of the opening it leads to, so the explorer can label the
    /// list without a second fetch. That denormalised copy has to match what the destination
    /// position actually says about itself, or the list promises a line the board disagrees with.
    /// </summary>
    [Test]
    public void EachMovesOpeningNameMatchesThePositionItLeadsTo()
    {
        var byKey = AllPositions().ToDictionary(p => p.Position.Key, p => p.Position, StringComparer.Ordinal);
        var engine = new Engine();
        var problems = new List<string>();

        foreach (OpeningPosition position in byKey.Values)
        {
            foreach (OpeningMove move in position.Moves.Where(m => m.Name is not null))
            {
                engine.SetPosition(position.Key + " 0 1");
                engine.GenerateValidMoves();
                if (!PuzzleData.TryApplyUci(engine, move.Uci)) continue;   // covered by the legality test

                string childKey = OpeningExplorer.KeyOf(engine.FEN);
                if (!byKey.TryGetValue(childKey, out OpeningPosition? child))
                {
                    problems.Add($"{position.Key} -{move.San} claims \"{move.Name}\" but {childKey} was not shipped");
                }
                else if (child.Name != move.Name)
                {
                    problems.Add($"{position.Key} -{move.San} says \"{move.Name}\", destination says \"{child.Name}\"");
                }

                if (problems.Count >= 5) break;
            }
            if (problems.Count >= 5) break;
        }

        Assert.That(problems, Is.Empty, string.Join("; ", problems));
    }

    [Test]
    public void TheStartingPositionOffersTheOpeningsAPlayerWouldExpect()
    {
        var byKey = AllPositions().ToDictionary(p => p.Position.Key, p => p.Position, StringComparer.Ordinal);
        string start = OpeningExplorer.KeyOf(ChessGameSession.StartingFen);

        Assert.That(byKey.ContainsKey(start), Is.True, "the starting position must be in the explorer");
        OpeningPosition root = byKey[start];

        Assert.Multiple(() =>
        {
            foreach (string opening in new[] { "e4", "d4", "c4", "Nf3" })
                Assert.That(root.Moves.Any(m => m.San == opening), Is.True, $"1.{opening} is missing from the root");

            // Ordered most-played first, which is what the UI relies on rather than sorting itself.
            var weights = root.Moves.Select(m => m.Weight).ToArray();
            Assert.That(weights, Is.Ordered.Descending, "moves must ship in descending popularity");
            Assert.That(root.Moves[0].San, Is.EqualTo("e4"), "1.e4 is the most played first move in the book");
        });
    }
}
